### ISSUE TITLE
Serial Exception Issue with Pololu Motor Controller

### ISSUE THREAD

**Issue by aditya-penumarti** [av-mae-uf/av1tenth#2]
The motor_driver/motor_controller node has issues with serial exception where the program is unable to write to the Pololu controller, this could be an issue with the baud rate or node rate. 

- [x] Need to confirm serial baud rate and implement a serial timeout. 
- [x] Need to confirm Pololu Config.

**Comment by patrick-neal** [comment]
Do you have a copy of the actual exception thrown?

**Comment by aditya-penumarti** [comment]
> Do you have a copy of the actual exception thrown?

I'll get you a screen shot of it tomorrow. From what I can remember is that it says it is an Input/Output Error and occurs on line 48 of the motor_driver/motor_controller

**Comment by patrick-neal** [comment]
Do you think the below could be the issue?

Firmware Version 1.04 for the Micro Maestro 6-Channel USB Servo Controller: This firmware version was released on 2019-06-10 for the Micro Maestro only. It fixes a bug where receiving a serial command could potentially interfere with the Maestro’s servo update routine, causing position updates for some servos to happen too soon or to be skipped entirely. **Repeated serial commands at high baud rates could also trap the Maestro in the servo update routine, causing it to become unresponsive**. This bug does not affect the Mini Maestros.

**Comment by aditya-penumarti** [comment]
That is possible but the driver doesn't request a servo position from any of the output channels. I'll try updating the firmware to check

**Comment by aditya-penumarti** [comment]
> Do you have a copy of the actual exception thrown?

`<pre>Traceback (most recent call last):
  File &quot;/home/gaither/.local/lib/python3.8/site-packages/serial/serialposix.py&quot;, line 621, in write
    n = os.write(self.fd, d)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &quot;/home/gaither/class_ws/install/motor_driver/lib/motor_driver/motor_controller&quot;, line 11, in &lt;module&gt;
    load_entry_point(&apos;motor-driver==1.0.0&apos;, &apos;console_scripts&apos;, &apos;motor_controller&apos;)()
  File &quot;/home/gaither/class_ws/install/motor_driver/lib/python3.8/site-packages/motor_driver/motor_controller.py&quot;, line 236, in main
    rclpy.spin(motor_controller)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rclpy/__init__.py&quot;, line 191, in spin
    executor.spin_once()
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py&quot;, line 718, in spin_once
    raise handler.exception()
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rclpy/task.py&quot;, line 239, in __call__
    self._handler.send(None)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py&quot;, line 429, in handler
    await call_coroutine(entity, arg)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py&quot;, line 354, in _execute_subscription
    await await_or_execute(sub.callback, msg)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py&quot;, line 118, in await_or_execute
    return callback(*args)
  File &quot;/home/gaither/class_ws/install/motor_driver/lib/python3.8/site-packages/motor_driver/motor_controller.py&quot;, line 221, in steering_angle_send
    self.pololu.set_speed(channel=steering_channel, speed=0)
  File &quot;/home/gaither/class_ws/install/motor_driver/lib/python3.8/site-packages/motor_driver/motor_controller.py&quot;, line 64, in set_speed
    self.cmd_out(cmd)
  File &quot;/home/gaither/class_ws/install/motor_driver/lib/python3.8/site-packages/motor_driver/motor_controller.py&quot;, line 48, in cmd_out
    self.serial_usb.write(bytes(cmd_out_byte, &quot;latin-1&quot;))
  File &quot;/home/gaither/.local/lib/python3.8/site-packages/serial/serialposix.py&quot;, line 655, in write
    raise SerialException(&apos;write failed: {}&apos;.format(e))
serial.serialutil.SerialException: write failed: [Errno 5] Input/output error
</pre>`
